on:
  push:
    branches:
    - master
    - dev
    - feature/github-actions 
    paths:
    - src/ApiGateways/*
    - .github/workflows/buildimages.yml
    - .github/workflows/multiarch.yml
    - .github/workflows/apigws/*
    - deploy/k8s/helm/apigwmm/*
    - deploy/k8s/helm/apigwms/*
    - deploy/k8s/helm/apigwwm/*
    - deploy/k8s/helm/apigwws/*
    paths-ignore:
    - src/ApiGateways/Mobile.Bff.Shopping/aggregator/*
    - src/ApiGateways/Web.Bff.Shopping/aggregator/*
jobs:
  PublishCharts:
    runs-on: ubuntu-16.04
    if: ne('${{ env.Build.Reason }}', 'PullRequest')
    steps:
    - uses: actions/checkout@v2
    - run: Copy '${{ github.workspace }}/deploy/k8s/helm/' '${{ github.workspace }}/deploy/k8s/helm'
      shell: powershell
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/deploy/k8s/helm
        name: helm