replicaCount: 1
clusterName: eshop-aks
pathBase: /webmarketingapigw

image:
  repository: envoyproxy/envoy
  tag: v1.11.1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/rewrite-target: "/"
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env: {}

envoy:
  configPath: /etc/envoy