name: eshoponcontainers-servicesandwebapps

extensions:
- name: zipkin

services:

- name: sqldata
  image: mcr.microsoft.com/mssql/server:2017-latest
  bindings:
  - port: 1433
    containerPort: 1433
  env:
  - name: ACCEPT_EULA
    value: Y
  - name: SA_PASSWORD
    value: Pass@word
  

- name: nosqldata
  image: mongo
  bindings:
  - port: 27017
    containerPort: 27017
  

- name: basketdata
  image: redis:alpine
  bindings:
  - port: 6379
    containerPort: 6379  

- name: rabbitmq
  image: rabbitmq:3-management-alpine
  bindings:
  - name: http-binding    
    port: 15672
    containerPort: 15672
  - name: amqp-binding
    port: 5672
    containerPort: 5672

- name: seq
  image: datalust/seq:latest
  bindings:
  - port: 5340
    containerPort: 80
  env:
  - name: ACCEPT_EULA
    value: Y

- name: identity-api
  include: Services/Identity/Identity.API/tye.yaml  

- name: catalog-api
  include: Services/Catalog/Catalog.API/tye.yaml  

- name: basket-api
  include: Services/Basket/Basket.API/tye.yaml 

- name: ordering-api
  include: Services/Ordering/Ordering.API/tye.yaml

- name: ordering-backgroundtasks
  include: Services/Ordering/Ordering.BackgroundTasks/tye.yaml

- name: marketing-api
  include: Services/Marketing/Marketing.API/tye.yaml  

- name: payment-api
  include: Services/Payment/Payment.API/tye.yaml

- name: locations-api
  include: Services/Location/Locations.API/tye.yaml

- name: webhooks-api
  include: Services/Webhooks/Webhooks.API/tye.yaml 

- name: mobileshoppingapigw
  image: envoyproxy/envoy:v1.11.1
  bindings:
  - name: http-port-80-binding
    port: 5200
    containerPort: 80
  - name: http-port-8001-binding
    port: 15200
    containerPort: 8001
  volumes:
    - source: ./ApiGateways/Envoy/config/mobileshopping
      target: /etc/envoy


- name: mobilemarketingapigw
  image: envoyproxy/envoy:v1.11.1
  bindings:
  - name: http-port-80-binding
    port: 5201
    containerPort: 80
  - name: http-port-8001-binding
    port: 15201
    containerPort: 8001
  volumes:
    - source: ./ApiGateways/Envoy/config/mobilemarketing
      target: /etc/envoy

- name: webshoppingapigw
  image: envoyproxy/envoy:v1.11.1
  bindings:
  - name: http-port-80-binding
    port: 5202
    containerPort: 80
  - name: http-port-8001-binding
    port: 15202
    containerPort: 8001
  volumes:
    - source: ./ApiGateways/Envoy/tye-config/webshopping
      target: /etc/envoy

- name: webmarketingapigw
  image: envoyproxy/envoy:v1.11.1
  bindings:
  - name: http-port-80-binding
    port: 5203
    containerPort: 80
  - name: http-port-8001-binding
    port: 15203
    containerPort: 8001
  volumes:
    - source: ./ApiGateways/Envoy/tye-config/webmarketing
      target: /etc/envoy

- name: mobileshoppingagg
  include: ApiGateways/Mobile.Bff.Shopping/aggregator/tye.yaml
  
- name: webshoppingagg
  include: ApiGateways/Web.Bff.Shopping/aggregator/tye.yaml

- name: ordering-signalrhub
  include: Services/Ordering/Ordering.SignalrHub/tye.yaml  

- name: webstatus
  include: Web/WebStatus/tye.yaml  

- name: webmvc
  include: Web/WebMVC/tye.yaml 

- name: webspa
  include: Web/WebSPA/tye.yaml  

- name: webhooks-client
  include: Web/WebhookClient/tye.yaml  