name: basket-api

on:
  push:
    branches:
    - master
    - dev
    - feature/github-actions
    paths:
    - src/BuildingBlocks/*
    - src/Services/Basket/*
    - .github/workflows/basket-api.yml
env:
  registryEndpoint: hub.docker.com/repository/docker/borjasanes/eshoponcontainers
  services: basket-api
  image: basket.api
  # branch: $(echo ${GITHUB_REF#refs/heads/})

jobs:
  BuildContainersForPR_Linux:
    runs-on: ubuntu-16.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Compose build ${{ env.services  }}
      run: docker-compose build -f src/docker-compose.yml ${{ env.services  }}
      shell: bash
      env:
        TAG: ${{ env.branch }}
        REGISTRY: ${{ env.registryEndpoint }}
  BuildContainersForPR_Windows:
    runs-on: windows-2019
    if:  ${{ false }}
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Compose build ${{ env.services  }}
      run: docker-compose build -f src/docker-compose.yml ${{ env.services  }}
      shell: pwsh
      env:
        TAG: ${{ env.branch }}
        REGISTRY: ${{ env.registryEndpoint }}
        PLATFORM: win
        NODE_IMAGE: stefanscherer/node-windows:10
  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: 
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Get branch name
      run: |
        currentbranch=$(echo ${GITHUB_REF##*/})
        echo "running on $currentbranch"
        echo "branch=$currentbranch" >> $GITHUB_ENV
        echo "TAG=$currentbranch" >> $GITHUB_ENV
      shell: bash

    - name: Compose build ${{ env.services }}
      run: |
        sudo -E docker-compose build ${{ env.services }}
        docker images
      working-directory: ./src
      shell: bash
      env:
      #   TAG: ${{ env.branch }}
        REGISTRY: ${{ env.registryEndpoint }}

    - name: Compose push ${{ env.image  }}
      run: sudo -E docker-compose push ${{ env.services }}
      working-directory: ./src
      shell: bash

  BuildWindows:
    runs-on: windows-2019
    if:  ${{ false }}
    # if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Compose build ${{ env.services  }}
      run: docker-compose build -f src/docker-compose.yml ${{ env.services  }}
      shell: pwsh
      env:
        TAG: ${{ env.branch }}
        REGISTRY: ${{ env.registryEndpoint }}
    - name: Compose push ${{ env.image  }}
      run: docker-compose push -f src/docker-compose.yml ${{ env.services }}'
      shell: pwsh
      env:
        TAG: ${{ env.branch }}
        REGISTRY: ${{ env.registryEndpoint }}