env:
  image: ''
  branch: ''
  registry: eshop
  registryEndpoint: ''
jobs:
  manifest:
    runs-on: Ubuntu 16.04
    needs:
    - BuildLinux
    if: and(,ne('${{ env.variables['Build.Reason']  }}', 'PullRequest'))
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: docker login
    - name: Create multiarch manifest
      run: |
        mkdir -p ~/.docker
        sed '$ s/.$//' $DOCKER_CONFIG/config.json > ~/.docker/config.json
        echo ',"experimental": "enabled" }' >> ~/.docker/config.json
        docker --config ~/.docker manifest create ${{ env.parameters.registry  }}/${{ env.parameters.image  }}:${{ env.parameters.branch  }} ${{ env.parameters.registry  }}/${{ env.parameters.image  }}:linux-${{ env.parameters.branch  }}
        docker --config ~/.docker manifest create ${{ env.parameters.registry  }}/${{ env.parameters.image  }}:latest ${{ env.parameters.registry  }}/${{ env.parameters.image  }}:linux-latest
        docker --config ~/.docker manifest push ${{ env.parameters.registry  }}/${{ env.parameters.image  }}:${{ env.parameters.branch  }}
        docker --config ~/.docker manifest push ${{ env.parameters.registry  }}/${{ env.parameters.image  }}:latest
      shell: bash